<a href="https://colab.research.google.com/github/engageintellect/AI-ML/blob/main/PyTorchCourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


# Introduction to Tensors
## Creating tensors

PyTorch tensors are created using torch.Tensor()


In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [13]:
# Get scalar as python int
scalar.item()

7

In [14]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [16]:
vector.shape

torch.Size([2])

In [17]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX[0]

tensor([7, 8])

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


# Creating Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with random numbers, then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [25]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3212, 0.6304, 0.9522, 0.8582],
        [0.8405, 0.0369, 0.4248, 0.5119],
        [0.6302, 0.1202, 0.8616, 0.8375]])

In [26]:
random_tensor.ndim

2

In [27]:
random_tensor.shape

torch.Size([3, 4])

In [29]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Creating Tensors with Zeros and Ones

In [ ]:
#